### ISSUE TITLE
python setup.py install raises ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by scls19fr** [wavexx/gtabview#5]
Hello,

    $ python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing top-level names to gtabview.egg-info/top_level.txt
    writing requirements to gtabview.egg-info/requires.txt
    writing dependency_links to gtabview.egg-info/dependency_links.txt
    writing gtabview.egg-info/PKG-INFO
    writing manifest file 'gtabview.egg-info/SOURCES.txt'
    installing library code to build/bdist.macosx-10.5-x86_64/egg
    running install_lib
    running build_py
    installing scripts to build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts
    running install_scripts
    running build_scripts
    changing mode of build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts/gtabview to 755
    copying gtabview.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
    copying gtabview.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
    copying gtabview.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
    copying gtabview.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
    copying gtabview.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
    zip_safe flag not set; analyzing archive contents...
    Traceback (most recent call last):
      File "setup.py", line 40, in <module>
        setup_requires=['setuptools_git'])
      File "//anaconda/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "//anaconda/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "//anaconda/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/install.py", line 67, in run
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/install.py", line 109, in do_egg_install
      File "//anaconda/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "//anaconda/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/bdist_egg.py", line 208, in run
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/bdist_egg.py", line 244, in zip_safe
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/bdist_egg.py", line 354, in analyze_egg
      File "//anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/setuptools/command/bdist_egg.py", line 391, in scan_module
    ValueError: bad marshal data (unknown type code)

I'm using Mac OS X 10.10 with Anaconda3 (Python 3 by default)

Kind regards

**Comment by wavexx** [comment]
I think there's something wrong in the egg of setuptools-git.
Try doing a pip install setuptools_git manually.

I'll maybe remove the dependency for setuptools/git in the future for a "big" release, but for development it's handy to have.

**Comment by scls19fr** [comment]
I git pull and removed `build`, `dist` and `gtabview.egg-info`directories.

    $ python setup.py install

is now working fine (with Python 3)

    import pandas as pd
    df = pd.DataFrame([[1, 2, 3], [4, 5, 6]],
        columns=['a', 'b', 'c'], index=['x', 'y'])
    view(df)

works fine too with Python 3
